'use client';

import { useEffect, useRef, useState, useCallback } from 'react';

interface LegalModalProps {
  type: 'privacy' | 'tos';
  onClose: () => void;
}

const PRIVACY_CONTENT = (
  <div className="space-y-8">
    <div>
      <h2 className="text-2xl font-bold text-blue-400 mb-3">Privacy Policy</h2>
      <p className="text-white/50 text-sm">Last updated: 12 April 2026</p>
    </div>

    <div className="p-4 rounded-xl border border-blue-500/30 bg-blue-500/5">
      <p className="text-blue-300 font-semibold text-lg mb-1">🔒 The short version</p>
      <p className="text-white/80">
        You provide data. We encrypt it at the field level before it hits our database. We don&apos;t read it,
        sell it, or trade it. If you supply your own passphrase,{' '}
        <strong>we derive a key from it and encrypt your data with that — meaning even we cannot decrypt it.</strong>
      </p>
    </div>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">1. What Data We Collect</h3>
      <p className="text-white/70 mb-3">
        UEFN DevKit only stores data that <strong>you explicitly provide</strong> through bot commands or website interactions.
        We do not passively collect, track, or harvest any data. The following fields are what we store
        (and what gets encrypted — see Section 2):
      </p>
      <p className="text-white/70 mb-3">
        This includes data generated by Discord bot features such as customer management,
        island analytics, session handling, Verse script uploads, seller profile management, redeem codes,
        reports, Fortnite tracking, bulk operations, and premium subscriptions.
      </p>
      <ul className="space-y-2 text-white/70 list-disc list-inside">
        <li>Customer records you create via <code className="text-cyan-400">/customer add</code> — stored in the <code className="text-cyan-400">customer_data</code> field</li>
        <li>Seller profile info from <code className="text-cyan-400">/seller create</code> — bio, contact method, website email</li>
        <li>Verse scripts you upload via <code className="text-cyan-400">/verse</code> — code content and Pastebin URL</li>
        <li>Redeem codes — feature grants and grant strings</li>
        <li>Guild/server settings you configure</li>
        <li>Reports filed via <code className="text-cyan-400">/report</code> — details field</li>
        <li>Fortnite island analytics and tracking data</li>
        <li>Session data for service delivery</li>
        <li>Premium subscription and Patreon integration data</li>
      </ul>
      <p className="text-white/60 mt-3 text-sm">
        We do <strong className="text-white">not</strong> collect your messages, voice activity, IP addresses,
        browsing history, or anything beyond what you explicitly submit through a bot command or website form.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">1.1 Website Data Collection</h3>
      <p className="text-white/70 mb-3">
        When you use our website, we collect the following data to provide authentication and services:
      </p>
      <ul className="space-y-2 text-white/70 list-disc list-inside">
        <li>Discord account information (user ID, username, display name, avatar) obtained through OAuth for login</li>
        <li>Email address from Discord OAuth (used for account verification and communications)</li>
        <li>Guild/server membership data to verify access permissions</li>
        <li>Session cookies for maintaining login state and security</li>
        <li>Patreon account data when linking for premium features</li>
      </ul>
      <p className="text-white/70 mb-3">
        Additionally, with your consent, we use Google Analytics to collect anonymous usage data such as page views,
        user interactions, and site performance metrics to improve our services.
      </p>
      <p className="text-white/60 text-sm">
        All website data is handled securely and only used for the purposes stated. You can manage cookie preferences
        at any time through our cookie consent banner.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">2. How Encryption Works</h3>
      <p className="text-white/70 mb-4">
        Sensitive fields are encrypted <strong>before</strong> they are written to the database using
        {' '}<strong>Fernet symmetric encryption</strong> (AES-128-CBC with HMAC-SHA256 for integrity).
        This happens at the field level — only the columns listed above are encrypted, not the entire row.
      </p>

      <div className="space-y-3">
        <div className="p-3 rounded-lg bg-white/5 border border-white/10">
          <p className="text-white font-semibold text-sm">🔐 Server-Side Key (default)</p>
          <p className="text-white/60 text-sm mt-1">
            By default, data is encrypted using a Fernet key stored in our server environment.
            This means we hold the key and could theoretically decrypt your data — but we don&apos;t,
            and we have no reason to.
          </p>
        </div>
        <div className="p-3 rounded-lg bg-blue-500/10 border border-blue-500/30">
          <p className="text-blue-300 font-semibold text-sm">🗝️ Your Own Passphrase (optional — true zero-knowledge)</p>
          <p className="text-white/60 text-sm mt-1">
            If you supply your own passphrase or Fernet key, we derive an encryption key from it using
            SHA-256 and use that to encrypt your data instead.{' '}
            <strong className="text-white">We never store your passphrase.</strong>{' '}
            Only you can decrypt the data. If you lose your passphrase, the data is permanently unreadable —
            not even we can recover it. This is true zero-knowledge encryption.
          </p>
        </div>
      </div>

      <p className="text-white/60 mt-4 text-sm">
        Fields encrypted per table: <code className="text-cyan-400">customers.customer_data</code>,{' '}
        <code className="text-cyan-400">seller_profiles.bio/website_email/contact_method</code>,{' '}
        <code className="text-cyan-400">verse_scripts.code/pastebin_url</code>,{' '}
        <code className="text-cyan-400">redeem_codes.feature/grant_string</code>,{' '}
        <code className="text-cyan-400">guild_settings.settings</code>,{' '}
        <code className="text-cyan-400">user_reports.details</code>.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">3. We Will Never Sell or Trade Your Data</h3>
      <p className="text-white/70 mb-3">We will <strong className="text-white">never</strong>:</p>
      <ul className="space-y-2 text-white/70 list-disc list-inside">
        <li>Sell your data to any third party</li>
        <li>Trade your data for any service or product</li>
        <li>Share your data with advertisers</li>
        <li>Use your data to train AI or machine learning models</li>
        <li>Monetize your data in any form</li>
        <li>Provide your data to data brokers</li>
        <li>Manually read or access your data for any purpose other than keeping the bot operational</li>
      </ul>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">4. When We May Be Required to Share Data</h3>
      <p className="text-white/70 mb-3">
        The only circumstances under which we may disclose data are:
      </p>
      <ul className="space-y-2 text-white/70 list-disc list-inside">
        <li>
          <strong className="text-white">Legal obligation</strong> — A valid court order, subpoena, or legal process
          compels us to. We will notify you if legally permitted.
          Note: if you used your own passphrase, the data is unreadable to us regardless.
        </li>
        <li>
          <strong className="text-white">Your explicit consent</strong> — You ask us to share specific data
          with a specific party for a specific purpose.
        </li>
        <li>
          <strong className="text-white">Safety emergencies</strong> — To prevent imminent harm in a verified emergency.
        </li>
      </ul>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">5. Data Retention &amp; Deletion</h3>
      <p className="text-white/70">
        Your data is retained for as long as you use the bot. You can delete any data at any time using
        the <code className="text-cyan-400">/files</code> command or by contacting us. Upon server removal or
        an explicit deletion request, all associated data is permanently purged within 30 days.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">6. Third-Party Services</h3>
      <p className="text-white/70">
        UEFN DevKit runs on Discord&apos;s platform and stores data in Supabase (our database provider).
        Verse scripts may optionally be sent to Pastebin — only when you explicitly choose to during the{' '}
        <code className="text-cyan-400">/verse</code> command. Each of these services has its own privacy policy.
        We share only the minimum data necessary for each feature to function.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">7. Contact</h3>
      <p className="text-white/70">
        For privacy questions, data access requests, or deletion requests, reach us via our{' '}
        <a href="/contact" className="text-blue-400 hover:text-blue-300 underline">contact page</a>{' '}
        or our <a href="/discord" className="text-blue-400 hover:text-blue-300 underline">Discord server</a>.
        For website-specific privacy concerns, you can also manage your data through your account dashboard.
      </p>
    </section>
  </div>
);

const TOS_CONTENT = (
  <div className="space-y-8">
    <div>
      <h2 className="text-2xl font-bold text-blue-400 mb-3">Terms of Service</h2>
      <p className="text-white/50 text-sm">Last updated: 12 April 2026 · Effective immediately upon use of the bot.</p>
    </div>

    <div className="p-4 rounded-xl border border-yellow-500/30 bg-yellow-500/5">
      <p className="text-yellow-300 font-semibold text-lg mb-1">⚠️ The short version</p>
      <p className="text-white/80">
        Use the bot for what it&apos;s built for. Don&apos;t abuse it, don&apos;t try to use it as a storage bucket,
        and don&apos;t do anything illegal with it. Be decent. That&apos;s basically it.
      </p>
    </div>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h3>
      <p className="text-white/70">
        By adding UEFN DevKit to your Discord server or using any of its commands, you agree to these
        Terms of Service. If you do not agree, please remove the bot from your server and discontinue use.
        These terms apply to all users, server owners, administrators, and anyone who interacts with the bot.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">2. Permitted Use</h3>
      <p className="text-white/70 mb-3">UEFN DevKit is designed specifically for:</p>
      <ul className="space-y-2 text-white/70 list-disc list-inside">
        <li>Managing customers and service delivery within Discord communities</li>
        <li>Organizing island development and Verse scripts</li>
        <li>Tracking Fortnite UEFN island analytics</li>
        <li>Running secure service delivery sessions</li>
        <li>Managing seller profiles and reputation within the UEFN ecosystem</li>
        <li>Creating and managing redeem codes for features and grants</li>
        <li>Providing bulk import and export operations for data management</li>
        <li>Admin configuration including encryption settings and role management</li>
        <li>Premium subscription management and Patreon integration</li>
        <li>API access for advanced integrations</li>
        <li>File management and data export for personal record-keeping</li>
        <li>Using the companion website for dashboard access, authentication, and premium features</li>
        <li>Using new features safely and responsibly, including command audit logs, role sync, and improved search</li>
      </ul>
      <p className="text-white/70">
        The bot is not a general data dump tool; it is a community assistant. Abuse via spam, data scraping or circumventing Discord policy is prohibited.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">3. Prohibited Use</h3>
      <p className="text-white/70 mb-3">You may <strong className="text-white">not</strong> use UEFN DevKit to:</p>
      <ul className="space-y-2 text-white/70 list-disc list-inside">
        <li>Store arbitrary files, data, or content unrelated to the bot&apos;s intended purpose</li>
        <li>
          Use the bot as a general-purpose cloud storage service — it is a bot, not a database or file host.
          If you need persistent storage capabilities, upgrade to Premium where storage features are properly supported.
        </li>
        <li>Spam commands or intentionally abuse rate limits</li>
        <li>Attempt to access other servers&apos; data or exploit security vulnerabilities</li>
        <li>Use the bot in violation of Discord&apos;s own Terms of Service</li>
        <li>Automate commands in ways not intended by the bot&apos;s design</li>
        <li>Impersonate other users, sellers, or parties through the bot&apos;s systems</li>
        <li>Post illegal content, hate speech, or content that violates applicable laws</li>
        <li>Use the bot for any fraudulent, deceptive, or scam-related activities</li>
        <li>Reverse-engineer, copy, or attempt to replicate the bot&apos;s core functionality</li>
        <li>Circumvent bans, blocks, or suspensions imposed by us</li>
        <li>Use the bot in any server that violates Discord Community Guidelines</li>
        <li>Misuse the website for unauthorized access, scraping, or violating our privacy practices</li>
        <li>Share or distribute encryption keys or access credentials inappropriately</li>
      </ul>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">4. Storage &amp; Fair Use</h3>
      <p className="text-white/70 mb-3">
        UEFN DevKit provides data storage as a functional component of its features, not as a standalone
        service. Free tier users have usage limits designed for normal bot use.
      </p>
      <p className="text-white/70 mb-3">
        <strong className="text-white">If your intent is to use the bot primarily as a storage solution</strong>,
        please consider upgrading to Premium. Premium subscribers receive substantially higher storage allocations,
        priority data retention, and the infrastructure investment required to maintain those features.
      </p>
      <p className="text-white/70">
        We reserve the right to limit, throttle, or remove data stored in bad faith or outside the intended
        scope of the bot&apos;s features.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">5. Account &amp; Server Responsibility</h3>
      <p className="text-white/70">
        Server owners are responsible for how UEFN DevKit is used within their server. If a server is
        found to be using the bot in violation of these terms, the entire server may be suspended or banned
        from the bot. Ensure your moderators and admins understand these terms.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">6. Service Availability</h3>
      <p className="text-white/70">
        UEFN DevKit is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We do not guarantee 100% uptime.
        We may perform maintenance, updates, or experience outages. We are not liable for any losses
        resulting from service unavailability.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">7. Premium Subscriptions</h3>
      <p className="text-white/70 mb-3">
        Premium plans are billed as described on our pricing page. Subscriptions auto-renew unless cancelled.
        Refunds are available within 30 days of purchase if you are unsatisfied. We reserve the right to
        modify pricing with 30 days&apos; notice. Abuse of Premium features may result in termination without refund.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">8. Termination</h3>
      <p className="text-white/70">
        We reserve the right to suspend or permanently ban any server or user from UEFN DevKit at our
        discretion, particularly for violations of these terms. Upon termination, your data will be
        retained for 30 days then permanently deleted unless you request earlier deletion.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">9. Limitation of Liability</h3>
      <p className="text-white/70">
        UEFN DevKit is not liable for any indirect, incidental, special, or consequential damages arising
        from your use of the bot, including but not limited to loss of data, lost profits, or service
        interruptions. Our total liability in any circumstance shall not exceed the amount you paid us in
        the 30 days preceding the claim.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">10. Changes to Terms</h3>
      <p className="text-white/70">
        We may update these terms from time to time. Material changes will be announced in our Discord
        server and reflected by an updated &quot;Last updated&quot; date at the top of this document. Continued use
        of the bot after changes constitutes acceptance of the new terms.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">11. Governing Law</h3>
      <p className="text-white/70">
        These terms are governed by applicable law. Any disputes shall be resolved through good-faith
        negotiation first. If unresolved, disputes may be submitted to binding arbitration.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-bold text-white mb-3">12. Contact</h3>
      <p className="text-white/70">
        Questions about these terms? Reach us via our{' '}
        <a href="/contact" className="text-blue-400 hover:text-blue-300 underline">contact page</a>{' '}
        or our <a href="/discord" className="text-blue-400 hover:text-blue-300 underline">Discord server</a>.
      </p>
    </section>
  </div>
);

export function LegalModal({ type, onClose }: LegalModalProps) {
  const overlayRef = useRef<HTMLDivElement>(null);
  const [isClosing, setIsClosing] = useState(false);

  const handleClose = useCallback(() => {
    setIsClosing(true);
    window.setTimeout(onClose, 200);
  }, [onClose]);

  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') handleClose();
    };
    document.addEventListener('keydown', handleKey);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', handleKey);
      document.body.style.overflow = '';
    };
  }, [handleClose]);

  return (
    <div
      ref={overlayRef}
      className="fixed inset-0 z-[100] flex items-center justify-center p-4"
      onClick={(e) => { if (e.target === overlayRef.current) handleClose(); }}
    >
      {/* Backdrop */}
      <div className={`absolute inset-0 bg-black/80 ${isClosing ? 'animate-fadeOut' : 'animate-fadeIn'}`} />

      {/* Modal */}
      <div className={`relative w-full max-w-3xl max-h-[85vh] flex flex-col rounded-2xl border border-white/10 bg-[#0a0a0a] shadow-2xl shadow-black/50 ${isClosing ? 'animate-scaleOut' : 'animate-scaleIn'}`}>
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-white/10 flex-shrink-0">
          <div className="flex items-center gap-3">
            <span className="text-2xl">{type === 'privacy' ? '🔒' : '📄'}</span>
            <span className="text-white font-bold text-lg">
              {type === 'privacy' ? 'Privacy Policy' : 'Terms of Service'}
            </span>
          </div>
          <button
            onClick={handleClose}
            className="w-8 h-8 flex items-center justify-center rounded-lg text-white/50 hover:text-white hover:bg-white/10 transition-all text-xl"
            aria-label="Close"
          >
            ×
          </button>
        </div>

        {/* Scrollable content */}
        <div className="overflow-y-auto p-6 flex-1 overscroll-contain hide-scrollbar">
          {type === 'privacy' ? PRIVACY_CONTENT : TOS_CONTENT}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-white/10 flex-shrink-0 flex justify-end">
          <button
            onClick={handleClose}
            className="px-6 py-2 bg-gradient-to-r from-blue-500 to-cyan-500 text-white font-semibold rounded-lg hover:shadow-lg hover:shadow-blue-500/30 transition-all"
          >
            Got it
          </button>
        </div>
      </div>
    </div>
  );
}