export interface ApiEndpoint {
  path: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  description: string;
  category: string;
  auth: boolean;
  premium: boolean;
  details: string;
  examples: string[];
  relatedEndpoints: string[];
}

export const apiEndpoints: Record<string, ApiEndpoint> = {
  'health': {
    path: '/api/health',
    method: 'GET',
    description: 'Check the health status of the service',
    category: 'System',
    auth: false,
    premium: false,
    details: 'Returns the current health status of the application and its dependencies.',
    examples: ['GET /api/health'],
    relatedEndpoints: ['stats'],
  },
  'guilds': {
    path: '/api/guilds',
    method: 'GET',
    description: 'Get information about Discord guilds',
    category: 'Discord',
    auth: true,
    premium: false,
    details: 'Retrieves information about the Discord guilds the bot is connected to.',
    examples: ['GET /api/guilds'],
    relatedEndpoints: ['guild-settings'],
  },
  'guild-settings': {
    path: '/api/v1/guild-settings',
    method: 'GET',
    description: 'Get or update guild settings',
    category: 'Discord',
    auth: true,
    premium: false,
    details: 'Retrieve or modify settings for a specific Discord guild.',
    examples: ['GET /api/v1/guild-settings?guildId=123456789'],
    relatedEndpoints: ['guilds'],
  },
  'customers': {
    path: '/api/v1/customers',
    method: 'GET',
    description: 'Manage customer data',
    category: 'Business',
    auth: true,
    premium: true,
    details: 'CRUD operations for customer management including adding, updating, and retrieving customer information.',
    examples: ['GET /api/v1/customers', 'POST /api/v1/customers'],
    relatedEndpoints: ['reports'],
  },
  'reports': {
    path: '/api/v1/reports',
    method: 'GET',
    description: 'Generate and retrieve reports',
    category: 'Business',
    auth: true,
    premium: true,
    details: 'Create and fetch various business reports and analytics.',
    examples: ['GET /api/v1/reports/sales', 'POST /api/v1/reports/generate'],
    relatedEndpoints: ['customers', 'stats'],
  },
  'stats': {
    path: '/api/v1/stats',
    method: 'GET',
    description: 'Get system statistics',
    category: 'System',
    auth: true,
    premium: false,
    details: 'Retrieve various statistics about the system usage and performance.',
    examples: ['GET /api/v1/stats/overview'],
    relatedEndpoints: ['health', 'reports'],
  },
  'verse': {
    path: '/api/v1/verse',
    method: 'GET',
    description: 'Verse-related operations',
    category: 'UEFN',
    auth: true,
    premium: false,
    details: 'Operations related to Verse scripting and UEFN development.',
    examples: ['GET /api/v1/verse/scripts'],
    relatedEndpoints: ['verse-scripts', 'island'],
  },
  'verse-scripts': {
    path: '/api/v1/verse-scripts',
    method: 'GET',
    description: 'Manage Verse scripts',
    category: 'UEFN',
    auth: true,
    premium: false,
    details: 'Upload, download, and manage Verse scripts for UEFN projects.',
    examples: ['GET /api/v1/verse-scripts', 'POST /api/v1/verse-scripts/upload'],
    relatedEndpoints: ['verse', 'files'],
  },
  'island': {
    path: '/api/v1/island',
    method: 'GET',
    description: 'Legacy island proxy endpoint',
    category: 'UEFN',
    auth: true,
    premium: false,
    details: 'Deprecated endpoint. Use /api/v1/island/lookup and /api/v1/island/predict instead.',
    examples: ['GET /api/v1/island/lookup?island_code=1234-1234-1234', 'GET /api/v1/island/predict?island_code=1234-1234-1234'],
    relatedEndpoints: ['verse', 'trackers'],
  },
  'island-lookup': {
    path: '/api/v1/island/lookup',
    method: 'GET',
    description: 'Island lookup by code',
    category: 'UEFN',
    auth: true,
    premium: true,
    details: 'Fetch detailed statistics for a Fortnite Creative island from the premium discovery analysis API.',
    examples: ['GET /api/v1/island/lookup?island_code=1234-1234-1234'],
    relatedEndpoints: ['island-predict'],
  },
  'island-predict': {
    path: '/api/v1/island/predict',
    method: 'GET',
    description: 'Island discovery prediction',
    category: 'UEFN',
    auth: true,
    premium: true,
    details: 'Get AI-powered discovery probability and optimization advice for a Fortnite Creative island.',
    examples: ['GET /api/v1/island/predict?island_code=1234-1234-1234'],
    relatedEndpoints: ['island-lookup'],
  },
  'trackers': {
    path: '/api/v1/trackers',
    method: 'GET',
    description: 'Manage island trackers',
    category: 'UEFN',
    auth: true,
    premium: false,
    details: 'Configure and monitor island tracking systems.',
    examples: ['GET /api/v1/trackers'],
    relatedEndpoints: ['island'],
  },
  'files': {
    path: '/api/v1/files',
    method: 'GET',
    description: 'File management operations',
    category: 'Storage',
    auth: true,
    premium: false,
    details: 'Upload, download, and manage files in the system.',
    examples: ['GET /api/v1/files/list', 'POST /api/v1/files/upload'],
    relatedEndpoints: ['verse-scripts'],
  },
  'quota': {
    path: '/api/v1/quota',
    method: 'GET',
    description: 'Check usage quotas',
    category: 'System',
    auth: true,
    premium: false,
    details: 'Check current usage against allocated quotas.',
    examples: ['GET /api/v1/quota'],
    relatedEndpoints: ['stats'],
  },
  'members': {
    path: '/api/v1/members',
    method: 'GET',
    description: 'Manage guild members',
    category: 'Discord',
    auth: true,
    premium: false,
    details: 'Operations related to Discord guild member management.',
    examples: ['GET /api/v1/members'],
    relatedEndpoints: ['guilds'],
  },
  'coupons': {
    path: '/api/v1/coupons',
    method: 'GET',
    description: 'Manage discount coupons',
    category: 'Business',
    auth: true,
    premium: true,
    details: 'Create and manage discount coupons for the service.',
    examples: ['GET /api/v1/coupons', 'POST /api/v1/coupons'],
    relatedEndpoints: ['customers'],
  },
  'fetch': {
    path: '/api/v1/fetch',
    method: 'GET',
    description: 'Fetch external data',
    category: 'Integration',
    auth: true,
    premium: false,
    details: 'Fetch data from external sources and APIs.',
    examples: ['GET /api/v1/fetch/epic-games'],
    relatedEndpoints: [],
  },
  'supabase': {
    path: '/api/v1/supabase',
    method: 'GET',
    description: 'Supabase database operations',
    category: 'Database',
    auth: true,
    premium: false,
    details: 'Direct operations on the Supabase database.',
    examples: ['GET /api/v1/supabase/query'],
    relatedEndpoints: [],
  },
  'admin': {
    path: '/api/v1/admin',
    method: 'GET',
    description: 'Administrative operations',
    category: 'Admin',
    auth: true,
    premium: false,
    details: 'Administrative functions and system management.',
    examples: ['GET /api/v1/admin/logs'],
    relatedEndpoints: [],
  },
  'command-logs': {
    path: '/api/command-logs',
    method: 'GET',
    description: 'Retrieve command execution logs',
    category: 'Admin',
    auth: true,
    premium: false,
    details: 'Get recent command logs from the Discord bot. Logs are automatically cleaned up after 12 hours.',
    examples: [
      'GET /api/command-logs',
      'GET /api/command-logs?limit=50',
      'GET /api/command-logs?guild_id=123456789&limit=100'
    ],
    relatedEndpoints: ['admin'],
  },
};