export interface Command {
  name: string;
  description: string;
  usage: string;
  category: string;
  permission: 'All' | 'Admin' | 'Manage Server' | 'Owner';
  premium: boolean;
  details: string;
  examples: string[];
  relatedCommands: string[];
}

// yea no way in hell im updating this again with alot of commands. im getting a "friend" to help me add the new commands.

export const commands: Record<string, Command> = {
  'help': {
    name: 'help',
    description: 'Show interactive help menu with all command categories',
    usage: '/help',
    category: 'General',
    permission: 'All',
    premium: false,
    details: 'Displays a paginated help menu showing all available commands organized by category. Use the navigation buttons to browse through different command categories.',
    examples: ['/help'],
    relatedCommands: ['premium', 'config info'],
  },
  'config-info': {
    name: 'config info',
    description: 'View server settings and current configuration',
    usage: '/config info',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'View your server\'s current configuration including enabled features, tier level, log channel, default customer role, and allowed admin roles.',
    examples: ['/config info'],
    relatedCommands: ['config sync', 'config refresh'],
  },
  'config-sync': {
    name: 'config sync',
    description: 'Force sync slash commands with Discord',
    usage: '/config sync',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Manually synchronize all slash commands with Discord. Useful after updates or if commands aren\'t appearing.',
    examples: ['/config sync'],
    relatedCommands: ['config info', 'config refresh'],
  },
  'config-refresh': {
    name: 'config refresh',
    description: 'Refresh poller after a tier upgrade',
    usage: '/config refresh',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Refreshes the island tracking poller system. Use this after upgrading to a higher tier for better performance.',
    examples: ['/config refresh'],
    relatedCommands: ['premium upgrade', 'config info'],
  },
  'config-set-log-channel': {
    name: 'config set log channel',
    description: 'Route bot activity logs to a channel',
    usage: '/config set-log-channel <channel>',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Set a specific channel where the bot will send activity logs and important notifications. Helps keep your server organized.',
    examples: ['/config set-log-channel #bot-logs'],
    relatedCommands: ['config info'],
  },
  'config-set-customer-role': {
    name: 'config set customer role',
    description: 'Set the default role for new customers',
    usage: '/config set-customer-role <role>',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Set a role that will be automatically assigned to new customers added via /customer add.',
    examples: ['/config set-customer-role @VIP'],
    relatedCommands: ['customer add', 'config info'],
  },
  'config-set-buildlog-key': {
    name: 'config set buildlog key',
    description: 'Set a per-server custom encryption key for build log data',
    usage: '/config set-buildlog-key <key>',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Set a custom encryption key specifically for build log data. This provides additional security for development notes.',
    examples: ['/config set-buildlog-key mysecretkey123'],
    relatedCommands: ['config clear-buildlog-key', 'config encryption-info'],
  },
  'config-clear-buildlog-key': {
    name: 'config clear buildlog key',
    description: 'Clear the custom per-server build log encryption key',
    usage: '/config clear-buildlog-key',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Remove the custom build log encryption key, falling back to the default encryption settings.',
    examples: ['/config clear-buildlog-key'],
    relatedCommands: ['config set-buildlog-key', 'config encryption-info'],
  },
  'config-encryption-info': {
    name: 'config encryption info',
    description: 'View encryption status and get setup help',
    usage: '/config encryption-info',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Display current encryption configuration and provide guidance on setting up data encryption for your server.',
    examples: ['/config encryption-info'],
    relatedCommands: ['config set-encryption', 'config encryption-status'],
  },
  'config-set-encryption': {
    name: 'config set encryption',
    description: 'Set your server\'s encryption key for data privacy',
    usage: '/config set-encryption <key>',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Configure a master encryption key for your server\'s sensitive data including customer information and build logs.',
    examples: ['/config set-encryption myencryptionkey'],
    relatedCommands: ['config encryption-info', 'config encryption-status'],
  },
  'config-encryption-status': {
    name: 'config encryption status',
    description: 'Check which encryption mode this server is using',
    usage: '/config encryption-status',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'View the current encryption status and which data types are being encrypted.',
    examples: ['/config encryption-status'],
    relatedCommands: ['config encryption-info', 'config set-encryption'],
  },
  'config-decrypt-data': {
    name: 'config decrypt data',
    description: 'Decrypt and view your server\'s encrypted data',
    usage: '/config decrypt-data',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Temporarily decrypt and display your server\'s encrypted data for verification or backup purposes.',
    examples: ['/config decrypt-data'],
    relatedCommands: ['config encryption-status', 'export data'],
  },
  'config-allowed-roles-add': {
    name: 'config allowed roles add',
    description: 'Allow a role to use admin commands',
    usage: '/config allowed-roles add <role>',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Add a role to the whitelist of roles allowed to use admin commands. Useful for giving non-admin staff permissions.',
    examples: ['/config allowed-roles add @Moderator'],
    relatedCommands: ['config allowed-roles remove', 'config info'],
  },
  'config-allowed-roles-remove': {
    name: 'config allowed roles remove',
    description: 'Disallow a role from admin commands',
    usage: '/config allowed-roles remove <role>',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Remove a role from the admin whitelist, revoking their access to admin commands.',
    examples: ['/config allowed-roles remove @Moderator'],
    relatedCommands: ['config allowed-roles add', 'config info'],
  },
  'customer-add': {
    name: 'customer add',
    description: 'Register a member as a customer',
    usage: '/customer add <member> <reason> [role]',
    category: 'Customer Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Add a member to your customer database with a reason (e.g., "Purchased Tier 1"). Optionally assign them a role. Great for tracking who purchased what.',
    examples: ['/customer add @John Purchased Premium', '/customer add @Jane Tier 1 Customer @VIP'],
    relatedCommands: ['customer remove', 'customer list', 'customer search'],
  },
  'customer-remove': {
    name: 'customer remove',
    description: 'Remove a customer record',
    usage: '/customer remove <member>',
    category: 'Customer Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Remove a member from the customer database.',
    examples: ['/customer remove @John'],
    relatedCommands: ['customer add', 'customer info'],
  },
  'customer-info': {
    name: 'customer info',
    description: 'View a specific customer\'s details',
    usage: '/customer info <member>',
    category: 'Customer Management',
    permission: 'Manage Server',
    premium: false,
    details: 'View detailed information about a customer including when they were added, the reason, and their current role.',
    examples: ['/customer info @John'],
    relatedCommands: ['customer list', 'customer search'],
  },
  'customer-list': {
    name: 'customer list',
    description: 'List all customers in this server',
    usage: '/customer list',
    category: 'Customer Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Display a paginated list of all customers in your server with their registration reason and date.',
    examples: ['/customer list'],
    relatedCommands: ['customer search', 'customer export'],
  },
  'customer-search': {
    name: 'customer search',
    description: 'Search customers by name or reason',
    usage: '/customer search <query>',
    category: 'Customer Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Search through your customer database by name or reason. Great for finding customers who purchased a specific item.',
    examples: ['/customer search Tier 1', '/customer search John'],
    relatedCommands: ['customer list', 'customer info'],
  },
  'customer-export': {
    name: 'customer export',
    description: 'Download all customers as a CSV file',
    usage: '/customer export',
    category: 'Customer Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Export your entire customer database as a CSV file for spreadsheet analysis or backup purposes.',
    examples: ['/customer export'],
    relatedCommands: ['customer list', 'export data customers'],
  },
  'bulkimport': {
    name: 'bulkimport',
    description: 'Bulk import server members as customers',
    usage: '/bulkimport <reason> [role]',
    category: 'Customer Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Quickly import multiple server members as customers at once based on your tier limits. Optionally assign them a role.',
    examples: ['/bulkimport Tier 1 Members @VIP'],
    relatedCommands: ['customer add', 'customer list'],
  },
  'coupon-add': {
    name: 'coupon add',
    description: 'Create a new coupon code',
    usage: '/coupon add <code> <description> [expires] [max_uses]',
    category: 'Coupon Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Create a new coupon code with optional expiry date and usage limits. Format dates as YYYY-MM-DD.',
    examples: ['/coupon add SUMMER50 "50% off" 2024-08-31 100', '/coupon add NOEXPIRY "Free item"'],
    relatedCommands: ['coupon list', 'coupon deactivate', 'checkcoupon'],
  },
  'coupon-list': {
    name: 'coupon list',
    description: 'View all coupons and their status',
    usage: '/coupon list',
    category: 'Coupon Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Display all your coupons with their code, description, usage count, expiry date, and current status.',
    examples: ['/coupon list'],
    relatedCommands: ['coupon add', 'coupon deactivate'],
  },
  'coupon-deactivate': {
    name: 'coupon deactivate',
    description: 'Immediately disable a coupon',
    usage: '/coupon deactivate <code>',
    category: 'Coupon Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Disable a coupon code immediately, preventing further usage.',
    examples: ['/coupon deactivate SUMMER50'],
    relatedCommands: ['coupon add', 'coupon list'],
  },
  'coupon-edit': {
    name: 'coupon edit',
    description: 'Edit an existing coupon code',
    usage: '/coupon edit <code> [description] [expires] [max_uses]',
    category: 'Coupon Management',
    permission: 'Manage Server',
    premium: false,
    details: 'Update a coupon\'s description, expiry date, or usage limits without recreating it.',
    examples: ['/coupon edit SUMMER50 description="60% off now!"'],
    relatedCommands: ['coupon add', 'coupon list'],
  },
  'checkcoupon': {
    name: 'checkcoupon',
    description: 'Check if a coupon code is valid (public)',
    usage: '/checkcoupon <code>',
    category: 'Coupon Management',
    permission: 'All',
    premium: false,
    details: 'Check if a coupon code is active, how many uses it has left, and when it expires. Everyone can use this!',
    examples: ['/checkcoupon SUMMER50'],
    relatedCommands: ['coupon add', 'coupon list'],
  },
  'verse': {
    name: 'verse',
    description: 'Upload and display a Verse script',
    usage: '/verse <script> <title> <upload_to_pastebin> [visibility] [expire]',
    category: 'Verse Script Management',
    permission: 'All',
    premium: false,
    details: 'Upload a Verse script file to Discord and optionally to Pastebin. Set visibility (Public/Unlisted/Private) and expiry time.',
    examples: ['/verse script.verse "My Island Script" true Public Never'],
    relatedCommands: ['verse-list', 'verse-delete'],
  },
  'verse-list': {
    name: 'verse-list',
    description: 'List all stored Verse scripts',
    usage: '/verse-list',
    category: 'Verse Script Management',
    permission: 'All',
    premium: false,
    details: 'View all Verse scripts that have been uploaded to your server with options to view or delete them.',
    examples: ['/verse-list'],
    relatedCommands: ['verse', 'verse-delete'],
  },
  'verse-delete': {
    name: 'verse-delete',
    description: 'Delete a stored Verse script',
    usage: '/verse-delete <script_id>',
    category: 'Verse Script Management',
    permission: 'All',
    premium: false,
    details: 'Delete a Verse script from storage. Get script IDs from /verse-list.',
    examples: ['/verse-delete 12345'],
    relatedCommands: ['verse', 'verse-list'],
  },
  'island': {
    name: 'island',
    description: 'Look up Fortnite island stats by code',
    usage: '/island <code>',
    category: 'Island Tracking',
    permission: 'All',
    premium: false,
    details: 'Look up live statistics for a Fortnite island including plays, players, session time, and retention metrics. Use the 4-4-4 format island code.',
    examples: ['/island 1234-5678-9012'],
    relatedCommands: ['fortnite-tracker'],
  },
  'buildlog-add': {
    name: 'buildlog add',
    description: 'Add an entry to the island dev diary',
    usage: '/buildlog add <entry>',
    category: 'Island Development',
    permission: 'All',
    premium: false,
    details: 'Create a build log entry documenting your island development progress. Great for tracking changes over time.',
    examples: ['/buildlog add "Added new obstacle course"'],
    relatedCommands: ['buildlog view', 'buildlog delete'],
  },
  'buildlog-view': {
    name: 'buildlog view',
    description: 'View the full build log history',
    usage: '/buildlog view [count]',
    category: 'Island Development',
    permission: 'All',
    premium: false,
    details: 'Display all build log entries for your island. Optionally limit the number of entries shown.',
    examples: ['/buildlog view', '/buildlog view 10'],
    relatedCommands: ['buildlog add', 'buildlog delete'],
  },
  'buildlog-delete': {
    name: 'buildlog delete',
    description: 'Delete a build log entry',
    usage: '/buildlog delete <entry_id>',
    category: 'Island Development',
    permission: 'All',
    premium: false,
    details: 'Remove a specific build log entry by its ID. Get IDs from /buildlog view.',
    examples: ['/buildlog delete 5'],
    relatedCommands: ['buildlog view', 'buildlog add'],
  },
  'task-add': {
    name: 'task add',
    description: 'Create a development task',
    usage: '/task add <title> [assignee]',
    category: 'Island Development',
    permission: 'All',
    premium: false,
    details: 'Create a task to track development work. Optionally assign it to a team member.',
    examples: ['/task add "Build battle arena" @Designer'],
    relatedCommands: ['task list', 'task done'],
  },
  'task-list': {
    name: 'task list',
    description: 'View all open tasks',
    usage: '/task list',
    category: 'Island Development',
    permission: 'All',
    premium: false,
    details: 'Display all active tasks with their assignees and completion status.',
    examples: ['/task list'],
    relatedCommands: ['task add', 'task done'],
  },
  'task-edit': {
    name: 'task edit',
    description: 'Edit a task',
    usage: '/task edit <task_id> [title] [assignee]',
    category: 'Island Development',
    permission: 'All',
    premium: false,
    details: 'Update a task\'s title or reassign it to another team member.',
    examples: ['/task edit 1 "Build battle arena v2" @Developer'],
    relatedCommands: ['task list', 'task add'],
  },
  'task-done': {
    name: 'task done',
    description: 'Mark a task as complete',
    usage: '/task done <task_id>',
    category: 'Island Development',
    permission: 'All',
    premium: false,
    details: 'Mark a task as completed. It will be removed from the active task list.',
    examples: ['/task done 1'],
    relatedCommands: ['task list', 'task add'],
  },
  'task-delete': {
    name: 'task delete',
    description: 'Delete a task',
    usage: '/task delete <task_id>',
    category: 'Island Development',
    permission: 'All',
    premium: false,
    details: 'Permanently remove a task from your task list.',
    examples: ['/task delete 1'],
    relatedCommands: ['task list', 'task done'],
  },
  'start-config': {
    name: 'start config',
    description: 'Configure the session system',
    usage: '/start config',
    category: 'Session System',
    permission: 'Admin',
    premium: false,
    details: 'Set up the session channel system for your server. Configure where service sessions are created.',
    examples: ['/start config'],
    relatedCommands: ['start begin', 'start exit'],
  },
  'start-begin': {
    name: 'start begin',
    description: 'Create or connect to a service session',
    usage: '/start begin [category]',
    category: 'Session System',
    permission: 'All',
    premium: false,
    details: 'Create a private session channel for service delivery. The bot will automatically set up permissions.',
    examples: ['/start begin', '/start begin Sales'],
    relatedCommands: ['start exit', 'start file'],
  },
  'start-images': {
    name: 'start images',
    description: 'Attach proof images to session',
    usage: '/start images <type>',
    category: 'Session System',
    permission: 'All',
    premium: false,
    details: 'Attach proof or delivery images to the current session channel.',
    examples: ['/start images attach', '/start images view'],
    relatedCommands: ['start file', 'start begin'],
  },
  'start-file': {
    name: 'start file',
    description: 'Attach delivery file to session',
    usage: '/start file <file>',
    category: 'Session System',
    permission: 'All',
    premium: false,
    details: 'Attach a delivery file (code, build, etc.) to the current session.',
    examples: ['/start file island_build.txt'],
    relatedCommands: ['start images', 'start begin'],
  },
  'start-exit': {
    name: 'start exit',
    description: 'Close and delete session channel',
    usage: '/start exit',
    category: 'Session System',
    permission: 'All',
    premium: false,
    details: 'End the current session. The channel will be deleted after confirmation.',
    examples: ['/start exit'],
    relatedCommands: ['start begin'],
  },
  'start-reassign-user': {
    name: 'start reassign-user',
    description: 'Reassign provider to a specific user (admin only)',
    usage: '/start reassign-user <user>',
    category: 'Session System',
    permission: 'Admin',
    premium: false,
    details: 'Reassign the provider role in the current session to a different user.',
    examples: ['/start reassign-user @NewProvider'],
    relatedCommands: ['start begin'],
  },
  'seller-dashboard': {
    name: 'seller dashboard',
    description: 'View and manage your seller profile',
    usage: '/seller dashboard',
    category: 'Seller Profiles',
    permission: 'All',
    premium: false,
    details: 'Access your seller dashboard to view stats, ratings, and manage your profile.',
    examples: ['/seller dashboard'],
    relatedCommands: ['seller edit', 'seller stats'],
  },
  'seller-create': {
    name: 'seller create',
    description: 'Create your seller profile',
    usage: '/seller create <bio>',
    category: 'Seller Profiles',
    permission: 'All',
    premium: false,
    details: 'Create a public seller profile visible to all servers using the bot.',
    examples: ['/seller create "Expert island builder with 5+ years experience"'],
    relatedCommands: ['seller edit', 'seller dashboard'],
  },
  'seller-edit': {
    name: 'seller edit',
    description: 'Edit your seller profile',
    usage: '/seller edit <bio> [contact]',
    category: 'Seller Profiles',
    permission: 'All',
    premium: false,
    details: 'Update your seller bio and contact information.',
    examples: ['/seller edit "Updated bio" @Discord user'],
    relatedCommands: ['seller create', 'seller dashboard'],
  },
  'seller-profile': {
    name: 'seller profile',
    description: 'View any seller\'s profile',
    usage: '/seller profile <user>',
    category: 'Seller Profiles',
    permission: 'All',
    premium: false,
    details: 'View another seller\'s public profile with their ratings and reviews.',
    examples: ['/seller profile @SellerName'],
    relatedCommands: ['seller rate'],
  },
  'seller-rate': {
    name: 'seller rate',
    description: 'Leave a review for a seller',
    usage: '/seller rate <user> <stars> <review>',
    category: 'Seller Profiles',
    permission: 'All',
    premium: false,
    details: 'Rate a seller 1-5 stars and leave a written review to help others.',
    examples: ['/seller rate @SellerName 5 "Great service, highly recommend!"'],
    relatedCommands: ['seller profile'],
  },
  'seller-stats': {
    name: 'seller stats',
    description: 'View your seller statistics',
    usage: '/seller stats',
    category: 'Seller Profiles',
    permission: 'All',
    premium: false,
    details: 'See your total sales, average rating, and other seller metrics.',
    examples: ['/seller stats'],
    relatedCommands: ['seller dashboard', 'seller profile'],
  },
  'list-providers': {
    name: 'list_providers',
    description: 'Browse all sellers',
    usage: '/list_providers [filter]',
    category: 'Seller Profiles',
    permission: 'All',
    premium: false,
    details: 'View the public directory of all active sellers with their ratings and specialties.',
    examples: ['/list_providers', '/list_providers island builders'],
    relatedCommands: ['seller profile'],
  },
  'member-lookup': {
    name: 'member lookup',
    description: 'View member join history',
    usage: '/member lookup <member>',
    category: 'Members & Invites',
    permission: 'Admin',
    premium: false,
    details: 'See when a member joined, who invited them, and their complete history.',
    examples: ['/member lookup @John'],
    relatedCommands: ['invitestats', 'member add'],
  },
  'member-add': {
    name: 'member add',
    description: 'Manually add a member record',
    usage: '/member add <member> [inviter] [reason]',
    category: 'Members & Invites',
    permission: 'Admin',
    premium: false,
    details: 'Manually create or update a member record with inviter information.',
    examples: ['/member add @John @Inviter "Direct invite"'],
    relatedCommands: ['member lookup'],
  },
  'invitestats': {
    name: 'invitestats',
    description: 'View all active invites',
    usage: '/invitestats',
    category: 'Members & Invites',
    permission: 'Admin',
    premium: false,
    details: 'See all active invite links and how many times each has been used.',
    examples: ['/invitestats'],
    relatedCommands: ['member lookup'],
  },  'inviteleaderboard': {
    name: 'inviteleaderboard',
    description: 'Show the top inviters ranked by members brought into the server',
    usage: '/inviteleaderboard',
    category: 'Members & Invites',
    permission: 'Manage Server',
    premium: false,
    details: 'Display a leaderboard of the top inviters in your server.',
    examples: ['/inviteleaderboard'],
    relatedCommands: ['invitestats', 'member lookup'],
  },  'report': {
    name: 'report',
    description: 'Report a user',
    usage: '/report <user> <reason>',
    category: 'Moderation',
    permission: 'All',
    premium: false,
    details: 'File a report against a user. Only works if you have an active session with them.',
    examples: ['/report @User "Scammed me"'],
    relatedCommands: [],
  },
  'redeem': {
    name: 'redeem',
    description: 'Redeem a code',
    usage: '/redeem <code>',
    category: 'Premium',
    permission: 'All',
    premium: false,
    details: 'Redeem a code for user or server features. Codes unlock premium features and benefits.',
    examples: ['/redeem ABC123XYZ'],
    relatedCommands: ['premium'],
  },
  'premium': {
    name: 'premium',
    description: 'Manage premium subscription',
    usage: '/premium [action]',
    category: 'Premium',
    permission: 'All',
    premium: false,
    details: 'View premium tier information, compare tiers, check your server\'s status, or upgrade.',
    examples: ['/premium', '/premium upgrade', '/premium compare'],
    relatedCommands: ['redeem'],
  },
  'files': {
    name: 'files',
    description: 'Browse and edit server data',
    usage: '/files',
    category: 'Files & Export',
    permission: 'Admin',
    premium: false,
    details: 'Access and edit your server\'s stored data files through an interactive file manager.',
    examples: ['/files'],
    relatedCommands: ['export data'],
  },
  'export-data': {
    name: 'export data',
    description: 'Export all server data',
    usage: '/export data <type>',
    category: 'Files & Export',
    permission: 'Admin',
    premium: false,
    details: 'Export specific data categories as JSON for backup or analysis. Types: all, customers, coupons, trackers, settings, members, verse.',
    examples: ['/export data all', '/export data customers'],
    relatedCommands: ['customer export', 'files'],
  },
  'stats': {
    name: 'stats',
    description: 'View a server-level dashboard with key metrics',
    usage: '/stats',
    category: 'Server Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Display an admin dashboard showing customers, coupons, islands, and members tracked.',
    examples: ['/stats'],
    relatedCommands: ['config info'],
  },
};

export function getCommandsByCategory(category: string): Command[] {
  return Object.values(commands).filter((cmd) => cmd.category === category);
}

export function getAllCategories(): string[] {
  const categories = new Set(Object.values(commands).map((cmd) => cmd.category));
  return Array.from(categories).sort();
}

export function getCommandByName(name: string): Command | undefined {
  // Convert URL format (hyphens) to command name format (spaces)
  // e.g., "config-info" -> "config info"
  const normalizedName = name.replace(/-/g, ' ');
  return Object.values(commands).find((cmd) => cmd.name === normalizedName);
}
