export interface Command {
  name: string;
  description: string;
  usage: string;
  category: string;
  permission: 'All' | 'Admin' | 'Manage Server' | 'Owner';
  premium: boolean;
  details: string;
  examples: string[];
  relatedCommands: string[];
}

export const commands: Record<string, Command> = {
  'help': {
    name: 'help',
    description: 'Show interactive help menu with all command categories',
    usage: '/help',
    category: 'Utilities',
    permission: 'All',
    premium: false,
    details: 'Displays a paginated help menu showing all available commands organized by category. Use the navigation buttons to browse through different command categories.',
    examples: ['/help'],
    relatedCommands: ['premium'],
  },
  'config-info': {
    name: 'config info',
    description: 'View server settings and current configuration',
    usage: '/config info',
    category: 'Configuration',
    permission: 'Admin',
    premium: false,
    details: 'View your server\'s current configuration including enabled features, tier level, log channel, default customer role, and allowed admin roles.',
    examples: ['/config info'],
    relatedCommands: ['config refresh', 'config log set'],
  },
  'config-sync': {
    name: 'config sync',
    description: 'Force sync slash commands with Discord',
    usage: '/config sync',
    category: 'Utilities',
    permission: 'Admin',
    premium: false,
    details: 'Manually synchronize all slash commands with Discord. Useful after updates or if commands aren\'t appearing.',
    examples: ['/config sync'],
    relatedCommands: ['config info'],
  },
  'config-refresh': {
    name: 'config refresh',
    description: 'Refresh poller after a tier upgrade',
    usage: '/config refresh',
    category: 'Utilities',
    permission: 'Admin',
    premium: false,
    details: 'Refreshes the island tracking poller system. Use this after upgrading to a higher tier for better performance.',
    examples: ['/config refresh'],
    relatedCommands: ['premium upgrade', 'config info'],
  },
  'config-log-set': {
    name: 'config log set',
    description: 'Route bot activity logs to a channel',
    usage: '/config log set <channel>',
    category: 'Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Set a specific channel where the bot will send activity logs and important notifications. Helps keep your server organized.',
    examples: ['/config log set #bot-logs'],
    relatedCommands: ['config info'],
  },
  'config-customer-role-set': {
    name: 'config customer-role set',
    description: 'Set the default role for new customers',
    usage: '/config customer-role set <role>',
    category: 'Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Set a role that will be automatically assigned to new customers added via /customer add.',
    examples: ['/config customer-role set @VIP'],
    relatedCommands: ['customer add', 'config info'],
  },
  'config-encryption-info': {
    name: 'config encryption info',
    description: 'View encryption status and get setup help',
    usage: '/config encryption info',
    category: 'Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Display current encryption configuration and provide guidance on setting up data encryption for your server.',
    examples: ['/config encryption info'],
    relatedCommands: ['config encryption set', 'config encryption status'],
  },
  'config-encryption-set': {
    name: 'config encryption set',
    description: 'Set your server\'s encryption key for data privacy',
    usage: '/config encryption set <key>',
    category: 'Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Configure a master encryption key for your server\'s sensitive data including customer information and build logs.',
    examples: ['/config encryption set myencryptionkey'],
    relatedCommands: ['config encryption info', 'config encryption status'],
  },
  'config-encryption-status': {
    name: 'config encryption status',
    description: 'Check which encryption mode this server is using',
    usage: '/config encryption status',
    category: 'Configuration',
    permission: 'Admin',
    premium: false,
    details: 'View the current encryption status and which data types are being encrypted.',
    examples: ['/config encryption status'],
    relatedCommands: ['config encryption info', 'config encryption set'],
  },
  'config-decrypt-data': {
    name: 'config decrypt data',
    description: 'Decrypt and view your server\'s encrypted data',
    usage: '/config decrypt data',
    category: 'Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Temporarily decrypt and display your server\'s encrypted data for verification or backup purposes.',
    examples: ['/config decrypt data'],
    relatedCommands: ['config encryption status', 'export data'],
  },
  'config-roles-add': {
    name: 'config roles add',
    description: 'Allow a role to use admin commands',
    usage: '/config roles add <role>',
    category: 'Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Add a role to the whitelist of roles allowed to use admin commands. Useful for giving non-admin staff permissions.',
    examples: ['/config roles add @Moderator'],
    relatedCommands: ['config roles remove', 'config info'],
  },
  'config-roles-remove': {
    name: 'config roles remove',
    description: 'Disallow a role from admin commands',
    usage: '/config roles remove <role>',
    category: 'Configuration',
    permission: 'Admin',
    premium: false,
    details: 'Remove a role from the admin whitelist, revoking their access to admin commands.',
    examples: ['/config roles remove @Moderator'],
    relatedCommands: ['config roles add', 'config info'],
  },
  'customer-add': {
    name: 'customer add',
    description: 'Register a member as a customer',
    usage: '/customer add <member> <reason> [role]',
    category: 'Customers',
    permission: 'Manage Server',
    premium: false,
    details: 'Add a member to your customer database with a reason (e.g., "Purchased Tier 1"). Optionally assign them a role. Great for tracking who purchased what.',
    examples: ['/customer add @John Purchased Premium', '/customer add @Jane Tier 1 Customer @VIP'],
    relatedCommands: ['customer remove', 'customer list', 'customer search'],
  },
  'customer-remove': {
    name: 'customer remove',
    description: 'Remove a customer record',
    usage: '/customer remove <member>',
    category: 'Customers',
    permission: 'Manage Server',
    premium: false,
    details: 'Remove a member from the customer database.',
    examples: ['/customer remove @John'],
    relatedCommands: ['customer add', 'customer info'],
  },
  'customer-info': {
    name: 'customer info',
    description: 'View a specific customer\'s details',
    usage: '/customer info <member>',
    category: 'Customers',
    permission: 'Manage Server',
    premium: false,
    details: 'View detailed information about a customer including when they were added, the reason, and their current role.',
    examples: ['/customer info @John'],
    relatedCommands: ['customer list', 'customer search'],
  },
  'customer-list': {
    name: 'customer list',
    description: 'List all customers in this server',
    usage: '/customer list',
    category: 'Customers',
    permission: 'Manage Server',
    premium: false,
    details: 'Display a paginated list of all customers in your server with their registration reason and date.',
    examples: ['/customer list'],
    relatedCommands: ['customer search', 'customer export'],
  },
  'customer-search': {
    name: 'customer search',
    description: 'Search customers by name or reason',
    usage: '/customer search <query>',
    category: 'Customers',
    permission: 'Manage Server',
    premium: false,
    details: 'Search through your customer database by name or reason. Great for finding customers who purchased a specific item.',
    examples: ['/customer search Tier 1', '/customer search John'],
    relatedCommands: ['customer list', 'customer info'],
  },
  'customer-export': {
    name: 'customer export',
    description: 'Download all customers as a CSV file',
    usage: '/customer export',
    category: 'Customers',
    permission: 'Manage Server',
    premium: false,
    details: 'Export your entire customer database as a CSV file for spreadsheet analysis or backup purposes.',
    examples: ['/customer export'],
    relatedCommands: ['customer list', 'export data customers'],
  },
  'patreon-setup': {
    name: 'patreon setup',
    description: 'Step-by-step Patreon connection guide',
    usage: '/patreon setup',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Guide you through connecting your Patreon account and token as required for integration features.',
    examples: ['/patreon setup'],
    relatedCommands: ['patreon toggle on', 'patreon sync'],
  },
  'patreon-toggle': {
    name: 'patreon toggle',
    description: 'Enable or disable Patreon integration',
    usage: '/patreon toggle <on|off>',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Enable or disable Patreon sync for this server.',
    examples: ['/patreon toggle on', '/patreon toggle off'],
    relatedCommands: ['patreon sync', 'patreon setup'],
  },
  'patreon-remove-data': {
    name: 'patreon remove data',
    description: 'Remove all Patreon integration data for this server',
    usage: '/patreon remove data',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Delete all Patreon-related configuration and sync records for this server. This is destructive and irreversible.',
    examples: ['/patreon remove data'],
    relatedCommands: ['patreon toggle off'],
  },
  'patreon-sync': {
    name: 'patreon sync',
    description: 'Force a manual sync of all Patreon members',
    usage: '/patreon sync',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Request an immediate update from Patreon for member status and role assignments.',
    examples: ['/patreon sync'],
    relatedCommands: ['patreon toggle on', 'patreon role assign'],
  },
  'patreon-inspect': {
    name: 'patreon inspect',
    description: 'Inspect a synced Patreon user by email',
    usage: '/patreon inspect <email>',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'View raw Patreon data for a synced member by email (requires Patreon integration).',
    examples: ['/patreon inspect user@example.com'],
    relatedCommands: ['patreon sync'],
  },
  'patreon-role-set': {
    name: 'patreon role set',
    description: 'Set role assignment for a Patreon tier or item',
    usage: '/patreon role set <type> <name> <role>',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Map a Patreon tier or item to a Discord role for auto-assignment. Type can be "tier" or "item".',
    examples: ['/patreon role set tier Bronze @BronzeMember', '/patreon role set item ExclusiveAddon @AddonRole'],
    relatedCommands: ['patreon role list', 'patreon role assign'],
  },
  'patreon-role-remove': {
    name: 'patreon role remove',
    description: 'Remove a Patreon tier or item role mapping',
    usage: '/patreon role remove <type> <name>',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Delete a tier or item mapping so the role is no longer auto-assigned. Type can be "tier" or "item".',
    examples: ['/patreon role remove tier Bronze', '/patreon role remove item ExclusiveAddon'],
    relatedCommands: ['patreon role list'],
  },
  'patreon-role-list': {
    name: 'patreon role list',
    description: 'List all Patreon tier or item role mappings',
    usage: '/patreon role list <type>',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Show all configured mappings between Patreon tiers/items and Discord roles. Type can be "tier" or "item".',
    examples: ['/patreon role list tier', '/patreon role list item'],
    relatedCommands: ['patreon role set'],
  },
  'patreon-role-assign': {
    name: 'patreon role assign',
    description: 'Assign Patreon roles to all synced members',
    usage: '/patreon role assign',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Apply role assignment based on stored Patreon tier/item data across all synced members.',
    examples: ['/patreon role assign'],
    relatedCommands: ['patreon sync'],
  },
  'patreon-configure-log': {
    name: 'patreon configure log',
    description: 'Configure optional Patreon verification log channel',
    usage: '/patreon configure log',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Choose a channel to receive logs for Patreon verification events.',
    examples: ['/patreon configure log'],
    relatedCommands: ['patreon sync', 'patreon role assign'],
  },
  'patreon-create-login-embed': {
    name: 'patreon create login embed',
    description: 'Create a Patreon login embed for member authentication',
    usage: '/patreon create login embed',
    category: 'Monetization',
    permission: 'Manage Server',
    premium: true,
    details: 'Generate a Discord embed with persistent buttons for user Patreon login and email linking.',
    examples: ['/patreon create login embed'],
    relatedCommands: ['patreon sync', 'patreon inspect'],
  },
  'bulkimport': {
    name: 'bulk import',
    description: 'Bulk import server members as customers',
    usage: '/bulk import <reason> [role]',
    category: 'Customers',
    permission: 'Manage Server',
    premium: false,
    details: 'Quickly import multiple server members as customers at once based on your tier limits. Optionally assign them a role.',
    examples: ['/bulk import Tier 1 Members @VIP'],
    relatedCommands: ['customer add', 'customer list'],
  },
  'verse': {
    name: 'verse',
    description: 'Upload and display a Verse script',
    usage: '/verse <script> <title> <upload_to_pastebin> [visibility] [expire]',
    category: 'Verse / UEFN',
    permission: 'All',
    premium: false,
    details: 'Upload a Verse script file to Discord and optionally to Pastebin. Set visibility (Public/Unlisted/Private) and expiry time.',
    examples: ['/verse script.verse "My Island Script" true Public Never'],
    relatedCommands: ['verse list', 'verse delete'],
  },
  'verse-list': {
    name: 'verse list',
    description: 'List all stored Verse scripts',
    usage: '/verse list',
    category: 'Verse / UEFN',
    permission: 'All',
    premium: false,
    details: 'View all Verse scripts that have been uploaded to your server with options to view or delete them.',
    examples: ['/verse list'],
    relatedCommands: ['verse', 'verse delete'],
  },
  'verse-delete': {
    name: 'verse delete',
    description: 'Delete a stored Verse script',
    usage: '/verse delete <script_id>',
    category: 'Verse / UEFN',
    permission: 'All',
    premium: false,
    details: 'Delete a Verse script from storage. Get script IDs from /verse list.',
    examples: ['/verse delete 12345'],
    relatedCommands: ['verse', 'verse list'],
  },
  'island': {
    name: 'island',
    description: 'Look up Fortnite island stats by code',
    usage: '/island <code>',
    category: 'Analytics',
    permission: 'All',
    premium: false,
    details: 'Look up live statistics for a Fortnite island including plays, players, session time, and retention metrics. Use the 4-4-4 format island code.',
    examples: ['/island 1234-5678-9012'],
    relatedCommands: ['stats'],
  },
  'session-config': {
    name: 'session config',
    description: 'Configure the session system',
    usage: '/session config',
    category: 'Sessions',
    permission: 'Admin',
    premium: false,
    details: 'Set up the session channel system for your server. Configure where service sessions are created.',
    examples: ['/session config'],
    relatedCommands: ['session start', 'session exit'],
  },
  'session-start': {
    name: 'session start',
    description: 'Create or connect to a service session',
    usage: '/session start [category]',
    category: 'Sessions',
    permission: 'All',
    premium: false,
    details: 'Create a private session channel for service delivery. The bot will automatically set up permissions.',
    examples: ['/session start', '/session start Sales'],
    relatedCommands: ['session exit', 'session file'],
  },
  'session-images': {
    name: 'session images',
    description: 'Attach proof images to session',
    usage: '/session images <type>',
    category: 'Sessions',
    permission: 'All',
    premium: false,
    details: 'Attach proof or delivery images to the current session channel.',
    examples: ['/session images attach', '/session images view'],
    relatedCommands: ['session file', 'session start'],
  },
  'session-file': {
    name: 'session file',
    description: 'Attach delivery file to session',
    usage: '/session file <file>',
    category: 'Sessions',
    permission: 'All',
    premium: false,
    details: 'Attach a delivery file (code, build, etc.) to the current session.',
    examples: ['/session file island_build.txt'],
    relatedCommands: ['session images', 'session start'],
  },
  'session-exit': {
    name: 'session exit',
    description: 'Close and delete session channel',
    usage: '/session exit',
    category: 'Sessions',
    permission: 'All',
    premium: false,
    details: 'End the current session. The channel will be deleted after confirmation.',
    examples: ['/session exit'],
    relatedCommands: ['session start'],
  },
  'session-reassign-user': {
    name: 'session reassign user',
    description: 'Reassign provider to a specific user (admin only)',
    usage: '/session reassign user <user>',
    category: 'Sessions',
    permission: 'Admin',
    premium: false,
    details: 'Reassign the provider role in the current session to a different user.',
    examples: ['/session reassign user @NewProvider'],
    relatedCommands: ['session start'],
  },
  'member-lookup': {
    name: 'member lookup',
    description: 'View member join history',
    usage: '/member lookup <member>',
    category: 'Utilities',
    permission: 'Admin',
    premium: false,
    details: 'See when a member joined, who invited them, and their complete history.',
    examples: ['/member lookup @John'],
    relatedCommands: ['invite stats', 'member add'],
  },
  'member-add': {
    name: 'member add',
    description: 'Manually add a member record',
    usage: '/member add <member> [inviter] [reason]',
    category: 'Utilities',
    permission: 'Admin',
    premium: false,
    details: 'Manually create or update a member record with inviter information.',
    examples: ['/member add @John @Inviter "Direct invite"'],
    relatedCommands: ['member lookup'],
  },
  'invite-stats': {
    name: 'invite stats',
    description: 'View all active invites',
    usage: '/invite stats',
    category: 'Utilities',
    permission: 'Admin',
    premium: false,
    details: 'See all active invite links and how many times each has been used.',
    examples: ['/invite stats'],
    relatedCommands: ['member lookup'],
  },
  'invite-leaderboard': {
    name: 'invite leaderboard',
    description: 'Show the top inviters ranked by members brought into the server',
    usage: '/invite leaderboard',
    category: 'Utilities',
    permission: 'Manage Server',
    premium: false,
    details: 'Display a leaderboard of the top inviters in your server.',
    examples: ['/invite leaderboard'],
    relatedCommands: ['invite stats', 'member lookup'],
  },
  'report': {
    name: 'report',
    description: 'Report a user',
    usage: '/report <user> <reason>',
    category: 'Utilities',
    permission: 'All',
    premium: false,
    details: 'File a report against a user. Only works if you have an active session with them.',
    examples: ['/report @User "Scammed me"'],
    relatedCommands: [],
  },
  'redeem': {
    name: 'redeem',
    description: 'Redeem a code',
    usage: '/redeem <code>',
    category: 'Monetization',
    permission: 'All',
    premium: false,
    details: 'Redeem a code for user or server features. Codes unlock premium features and benefits.',
    examples: ['/redeem ABC123XYZ'],
    relatedCommands: ['premium'],
  },
  'premium': {
    name: 'premium',
    description: 'Manage premium subscription',
    usage: '/premium [action]',
    category: 'Monetization',
    permission: 'All',
    premium: false,
    details: 'View premium tier information, compare tiers, check your server\'s status, or upgrade.',
    examples: ['/premium', '/premium upgrade', '/premium compare'],
    relatedCommands: ['redeem'],
  },
  'files': {
    name: 'files',
    description: 'Browse and edit server data',
    usage: '/files',
    category: 'Data & Export',
    permission: 'Admin',
    premium: false,
    details: 'Access and edit your server\'s stored data files through an interactive file manager.',
    examples: ['/files'],
    relatedCommands: ['export data'],
  },
  'export-data': {
    name: 'export data',
    description: 'Export all server data',
    usage: '/export data <type>',
    category: 'Data & Export',
    permission: 'Admin',
    premium: false,
    details: 'Export specific data categories as JSON for backup or analysis. Types: all, customers, trackers, settings, members, verse.',
    examples: ['/export data all', '/export data customers'],
    relatedCommands: ['customer export', 'files'],
  },
  'stats': {
    name: 'stats',
    description: 'View a server-level dashboard with key metrics',
    usage: '/stats',
    category: 'Analytics',
    permission: 'Admin',
    premium: false,
    details: 'Display an admin dashboard showing customers, islands, and members tracked.',
    examples: ['/stats'],
    relatedCommands: ['island'],
  },
};

export function getCommandsByCategory(category: string): Command[] {
  return Object.values(commands).filter((cmd) => cmd.category === category);
}

export function getAllCategories(): string[] {
  const categories = new Set(Object.values(commands).map((cmd) => cmd.category));
  return Array.from(categories).sort();
}

export function getCommandByName(name: string): Command | undefined {
  // Convert URL format (hyphens) to command name format (spaces)
  // e.g., "config-info" -> "config info"
  const normalizedName = name.replace(/-/g, ' ');
  return Object.values(commands).find((cmd) => cmd.name === normalizedName);
}
