export async function GET() {
  const tiers = [
    {
      default_tier: "free",
      update_interval_locked: true,
      min_poll_interval_seconds: 3600,
      free_max_fortnite_trackers: 3,
      free_max_customers: 1000,
      free_max_coupons: 20,
      free_max_verse_scripts: 50,
      free_fortnite_poll_interval: 3600,
      premium_max_fortnite_trackers: 10,
      premium_max_customers: 5000,
      premium_max_coupons: 100,
      premium_max_verse_scripts: 200,
      premium_fortnite_poll_interval: 720,
      enterprise_max_youtube_trackers: 30,
      enterprise_max_fortnite_trackers: 30,
      enterprise_max_customers: 99999,
      enterprise_max_coupons: 99999,
      enterprise_max_verse_scripts: 99999,
      enterprise_fortnite_poll_interval: 600,
      free_cmd_fortnite_tracker: true,
      free_cmd_customers: true,
      free_cmd_coupons: true,
      free_cmd_verse: true,
      free_cmd_invites: true,
      free_cmd_files: false,
      premium_cmd_youtube_tracker: true,
      premium_cmd_fortnite_tracker: true,
      premium_cmd_customers: true,
      premium_cmd_coupons: true,
      premium_cmd_verse: true,
      premium_cmd_invites: true,
      premium_cmd_files: true,
      premium_cmd_presence: true,
      enterprise_cmd_fortnite_tracker: true,
      enterprise_cmd_customers: true,
      enterprise_cmd_coupons: true,
      enterprise_cmd_verse: true,
      enterprise_cmd_invites: true,
      enterprise_cmd_files: true,
      enterprise_cmd_presence: true,
      free_verse_max_size_kb: 512,
      premium_verse_max_size_kb: 2048,
      enterprise_verse_max_size_kb: 2048,
      verse_auto_pastebin: true,
      invites_leaderboard_size: 15,
      customers_export_enabled: true,
      coupon_max_code_length: 32,
      updated_at: "2026-03-16T21:25:19+02:00",
      updated_by: "system"
    }
  ]

  return Response.json(tiers)
}
